# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Krait < Formula
  desc "Unified codebase health analyzer for Go"
  homepage "https://github.com/krait-go/krait"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/krait-go/krait/releases/download/v0.2.0/krait_darwin_amd64.tar.gz"
      sha256 "d9b41d0a846cdce45964dcb9cb91fea32db576b231085b17cdafee46f6630959"

      define_method(:install) do
        bin.install "krait"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/krait-go/krait/releases/download/v0.2.0/krait_darwin_arm64.tar.gz"
      sha256 "76fbae473e62728c458922b2bd087ac8f3daa3011ed1708bd04061cfd2c8e0a1"

      define_method(:install) do
        bin.install "krait"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/krait-go/krait/releases/download/v0.2.0/krait_linux_amd64.tar.gz"
      sha256 "647618dc7d5436f665b610c595adc9a935c22a7d4ebc95a6668c7dd1a64a0cb5"
      define_method(:install) do
        bin.install "krait"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/krait-go/krait/releases/download/v0.2.0/krait_linux_arm64.tar.gz"
      sha256 "f79a8cd6ca27990c2144b11610a948c0639592f0a3328bdef5f46e4fa51df8c4"
      define_method(:install) do
        bin.install "krait"
      end
    end
  end

  test do
    system bin/"krait", "--version"
  end
end
