# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Krait < Formula
  desc "Unified codebase health analyzer for Go"
  homepage "https://github.com/krait-go/krait"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/krait-go/krait/releases/download/v0.1.1/krait_darwin_amd64.tar.gz"
      sha256 "eb49c18e9694e2acbf03d72bb53c4330932fc83c9edd3d29da2c1e85e5fc390a"

      define_method(:install) do
        bin.install "krait"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/krait-go/krait/releases/download/v0.1.1/krait_darwin_arm64.tar.gz"
      sha256 "cdcfa75c0512e82b28715295b2c7cfd11492024d8ab92815e1ce0e523fd63d3e"

      define_method(:install) do
        bin.install "krait"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/krait-go/krait/releases/download/v0.1.1/krait_linux_amd64.tar.gz"
      sha256 "722e1283fe5ad134384f3229abbe50e8c44b15109103f9c6f8ea00b807ac0865"
      define_method(:install) do
        bin.install "krait"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/krait-go/krait/releases/download/v0.1.1/krait_linux_arm64.tar.gz"
      sha256 "f4a032f2000d4d8f6764e8329a135b11c3de48cb661d6c94a6db9f3750b90955"
      define_method(:install) do
        bin.install "krait"
      end
    end
  end

  test do
    system bin/"krait", "--version"
  end
end
